### ISSUE TITLE
[question] not operator in tests.webpack.js

### ISSUE THREAD

**Issue by samithaf** [zyml/es6-karma-jasmine-webpack-boilerplate#6]
Thanks for the boilerplate code and it's very helpful. I wonder how the not operator works in following use case given that, Regex does not support not operators in this format

**require.context('./src', true, /!(-test.js)$/);**

**Comment by zyml** [comment]
My bad there. I've changed the regex to be `/^((?!__tests__).)*.js$/`.

This is to also exclude files within the tests folder, which can be fixtures or utility modules.
